# -*- coding: utf-8 -*-
"""EDA_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYPrW6XxB897DiOCFcruo4LAUGWKpc_B
"""

# Commented out IPython magic to ensure Python compatibility.
# import python libraries

import numpy as np  # numpy
import pandas as pd # pandas
import matplotlib.pyplot as plt # visualizing data
# %matplotlib inline
import seaborn as sns # seaborn



# import csv file -- csv = comma separated Values
df = pd.read_csv('/content/Diwali Sales Data.csv', encoding= 'unicode_escape')

df.shape # rows x col.

df.head()

df.info()



#drop unrelated/blank columns
df.drop(['Status', 'unnamed1'], axis=1, inplace=True) # .drop , axis=1 , inplace=True

#check for null values
pd.isnull(df).sum() # .isnull(df).sum()

# drop null values
df.dropna(inplace=True) # .dropna , inplace=True

# change data type
df['Amount'] = df['Amount'].astype('int')  # .astype('int')

df['Amount'].dtypes # .dtypes

df.columns # .columns

#rename column
df.rename(columns= {'Marital_Status':'Marriage'}) # .rename

# describe() method returns description of the data in the DataFrame (i.e. count, mean, std, etc)
df.describe() #.describe()

# use describe() for specific columns
df[['Age', 'Orders', 'Amount']].describe() # .describe()

# Exploratory  Data Analysis - EDA

# plotting a bar chart for Gender and it's count
#Gender

ax = sns.countplot(x = 'Gender',data = df)

for bars in ax.containers:
    ax.bar_label(bars)


'''
If you have to plot a graph shbowing the total count of values based on categories or group you use these Type of Graphs.

-------------------------------------------------------------------------------------------------------------------------------
# plotting a bar chart for Gender and it's count
#Gender

ax = sns.countplot(x = 'Gender',data = df)

for bars in ax.containers:
    ax.bar_label(bars)


'''

# plotting a bar chart for gender vs total amount

sales_gen = df.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False) # .groupby() --> gender ke bases par group kar rha hai,  .sort_values,

sns.barplot(x = 'Gender',y= 'Amount' ,data = sales_gen) # .barplot

# Age
ax = sns.countplot(data = df, x = 'Age Group', hue = 'Gender') # .countplot

for bars in ax.containers:
    ax.bar_label(bars)

'''

ax = sns.countplot(data = df, x = 'Age Group', hue = 'Gender') # .countplot

for bars in ax.containers:
    ax.bar_label(bars)

'''

# Total Amount vs Age Group
sales_age = df.groupby(['Age Group'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.barplot(x = 'Age Group',y= 'Amount' ,data = sales_age) # .barplot

# States
# total number of orders from top 10 states
sales_state = df.groupby(['State'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10) # .head(10) --> will print top 10 states

sns.set(rc = {'figure.figsize':(20,5)}) # seaborrn ka styling function har , iski help se hum chart ka size set kar rhae hain. (sns.set(rc={'figure.figsize':(15,5)}))
sns.barplot(data = sales_state, x = 'State',y= 'Orders') # rc= runtime Configuration (rcParams)

# total amount/sales from top 10 states

sales_state = df.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(data = sales_state, x = 'State',y= 'Amount')

# Marital Status
ax = sns.countplot(data = df, x = 'Marital_Status') # .countplot

sns.set(rc={'figure.figsize':(7,5)})
for bars in ax.containers:
    ax.bar_label(bars)

'''
ax = sns.countplot(data = df, x = 'Marital_Status') # .countplot

sns.set(rc={'figure.figsize':(7,5)})
for bars in ax.containers:
    ax.bar_label(bars)

This codee will print the total count of any column you want in a graphical manner.

'''

sales_state = df.groupby(['Marital_Status', 'Gender'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data = sales_state, x = 'Marital_Status',y= 'Amount', hue='Gender') # .barplot()


'''
as_index=False --> jab bhi hum pandas  ke andar  .groupby() keyword ka use karte hain , toh vo columns ko bhi index ki trh treat karta hai , but columns ko hum index ki tarah treat nahi kar sakte , isiliye agar m as_index = TRUE PRINT KARVANA chahunga toh code mereko error throw kardega.

'''

#Occupation

sns.set(rc={'figure.figsize':(20,5)})
ax = sns.countplot(data = df, x = 'Occupation')

for bars in ax.containers:
    ax.bar_label(bars)

sales_state = df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Occupation',y= 'Amount')

# Product Category
sns.set(rc={'figure.figsize':(20,5)})
ax = sns.countplot(data = df, x = 'Product_Category')

for bars in ax.containers:
    ax.bar_label(bars)

sales_state = df.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by='Amount', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_Category',y= 'Amount')

sales_state = df.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by='Orders', ascending=False).head(10)

sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data = sales_state, x = 'Product_ID',y= 'Orders')

# top 10 most sold products (same thing as above)

fig1, ax1 = plt.subplots(figsize=(12,7))
df.groupby('Product_ID')['Orders'].sum().nlargest(10).sort_values(ascending=False).plot(kind='bar')

