# -*- coding: utf-8 -*-
"""EDA_FoodPanda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9kU7xjeBHGPNInFOPJWAW6c1q1qkySO
"""

# Commented out IPython magic to ensure Python compatibility.
#import python libraries
import pandas as pd #pandas
import numpy as np #numpy
import matplotlib.pyplot as plt#visualizing data
# %matplotlib inline
import seaborn as sns #seaborn

#foodpanda about frequency of people ordering food online
df=pd.read_csv('/content/Foodpanda Analysis Dataset.csv',encoding='unicode_escape')

df.shape

df.head()

df.tail()

df.info()

df.describe()

df.isnull().sum()

df['rating'].fillna(df['rating'].median())

df.isnull().sum()

df.describe()

df.rename(columns={'restaurant_name':'restaurant'},inplace=True)

df.columns

#plotting a bar chart for gender VS count
ax=sns.countplot(x='gender',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for Age VS count
ax=sns.countplot(x='age',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

# plotting a bar chart for city VS count
ax=sns.countplot(x='city',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for restaurant VS Count
ax=sns.countplot(x='restaurant',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for dish_name VS count
ax=sns.countplot(x='dish_name',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for category VS count
ax=sns.countplot(x='category',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for quantity VS count
ax=sns.countplot(x='quantity',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

df.rename(columns={'payment_method':'pay_method'},inplace=True)

#plotting a bar chart for pay_method VS count
ax=sns.countplot(x='pay_method',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

df.rename(columns={'order_frequency':'frequency'},inplace=True)

#plotting a bar chart for frequency VS count
plt.figure(figsize=(20,5))
ax=sns.countplot(x='frequency',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for loyalty_points VS count
plt.figure(figsize=(20,5))
ax=sns.countplot(x='loyalty_points',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for churned VS count
ax=sns.countplot(x='churned',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

#plotting a bar chart for rating VS count
ax=sns.countplot(x='rating',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

df.rename(columns={'delivery_status':'delivery'},inplace=True)

#plotting a bar chart for delivery VS count
ax=sns.countplot(x='delivery',data=df)

for bars in ax.containers:
  ax.bar_label(bars)

sales_gen=df.groupby(['age'],as_index=False)['price'].sum().sort_values(by='price',ascending=False )
sns.barplot(x='age',y='price',data=sales_gen)

sales_gen=df.groupby(['gender'],as_index=False)['price'].sum().sort_values(by='price',ascending=False )
sns.barplot(x='gender',y='price',data=sales_gen)

sales_gen=df.groupby(['city'],as_index=False)['age'].sum().sort_values(by='age',ascending=False )
sns.barplot(x='city',y='age',data=sales_gen)

ax=sns.countplot(x='age',data=df,hue='gender')
for bars in ax.containers:
  ax.bar_label(bars)

plt.figure(figsize=(20,6))
ax=sns.countplot(x='rating',data=df,hue='gender')
for bars in ax.containers:
  ax.bar_label(bars)

ax=sns.countplot(x='quantity',data=df,hue='gender')
for bars in ax.containers:
  ax.bar_label(bars)

plt.figure(figsize=(20,6))
ax=sns.countplot(x='frequency',data=df,hue='gender')
for bars in ax.containers:
  ax.bar_label(bars)